version: "3"

services: 
  db:
    image: postgres:12
    container_name: db
    env_file: .env
  
  backend:
    build: 
      context: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/orm
    ports: 
      - 8000:8000
    depends_on: 
      - db  