# Generated by Django 3.1.5 on 2021-04-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('nombre', 'tipo')},
        ),
    ]
